#!/usr/bin/env python3
"""Refresh the bibliography from NASA ADS.

Replaces the manual loop of: export BibTeX from the ADS web UI, paste it over
assets/data/soumya_publications.bib, hand-edit the citation_count fields, and
remember to bump the citations_updated date.

    export ADS_TOKEN=...              # https://ui.adsabs.harvard.edu/user/settings/token
    python3 scripts/sync_ads.py

What it does:
  1. asks ADS for every record matching the ORCID below,
  2. pulls the canonical BibTeX for those records from ADS's own exporter, so
     the file keeps exactly the format a manual export would have produced,
  3. writes each record's current citation_count into its entry,
  4. stamps the file with today's date,
  5. regenerates _data/publications.yml via scripts/bib_to_data.py.

Records listed in scripts/ads_exclude.txt are skipped, which is how you drop a
duplicate, an erratum, or a same-name mismatch without hand-editing the .bib.

Google Scholar is deliberately not used: it has no public API, its terms
prohibit scraping, and it blocks automated access in practice. ADS is also the
better source for this field — it indexes conference abstracts and has more
reliable citation counts for astronomy than Scholar or Crossref.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import pathlib
import re
import subprocess
import sys
import urllib.error
import urllib.parse
import urllib.request

ORCID = "0000-0003-0103-6569"
BIB = pathlib.Path("assets/data/soumya_publications.bib")
EXCLUDE = pathlib.Path("scripts/ads_exclude.txt")

API = "https://api.adsabs.harvard.edu/v1"
SEARCH_FIELDS = "bibcode,title,year,citation_count,doctype,doi"
# ADS doctypes that belong in the bibliography. Everything else (errata,
# catalogues, software records, press releases) is left out.
KEEP_DOCTYPES = {"article", "inproceedings", "abstract", "inbook", "book", "eprint"}


def api_get(path: str, params: dict, token: str) -> dict:
    url = f"{API}{path}?{urllib.parse.urlencode(params)}"
    req = urllib.request.Request(url, headers={"Authorization": f"Bearer {token}"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.load(r)


def api_post(path: str, payload: dict, token: str) -> dict:
    req = urllib.request.Request(
        f"{API}{path}",
        data=json.dumps(payload).encode(),
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=120) as r:
        return json.load(r)


def fetch_records(token: str) -> list[dict]:
    """Every ADS record for this ORCID, newest first."""
    records, start, rows = [], 0, 200
    while True:
        data = api_get(
            "/search/query",
            {
                "q": f"orcid:{ORCID}",
                "fl": SEARCH_FIELDS,
                "rows": rows,
                "start": start,
                "sort": "date desc",
            },
            token,
        )["response"]
        records.extend(data["docs"])
        start += rows
        if start >= data["numFound"]:
            return records


def fetch_bibtex(bibcodes: list[str], token: str) -> str:
    """ADS's own BibTeX export, so the file format matches a manual export."""
    return api_post("/export/bibtex", {"bibcode": bibcodes}, token)["export"]


def inject_citation_counts(bibtex: str, counts: dict[str, int]) -> str:
    """Add `citation_count = {N}` to each entry, replacing any existing value."""
    out, injected = [], 0
    for block in re.split(r"(?=@[A-Za-z]+\{)", bibtex):
        if not block.strip().startswith("@"):
            out.append(block)
            continue
        key = re.match(r"@[A-Za-z]+\{([^,]+),", block)
        if not key or key[1] not in counts:
            out.append(block)
            continue
        block = re.sub(r",?\n\s*citation_count\s*=\s*\{[^}]*\}", "", block)
        # Insert before the closing brace of the entry.
        idx = block.rstrip().rfind("}")
        block = (
            block[:idx].rstrip().rstrip(",")
            + f",\n      citation_count = {{{counts[key[1]]}}}\n"
            + block[idx:]
        )
        injected += 1
        out.append(block)
    print(f"  citation counts written into {injected} entries")
    return "".join(out)


def header(today: str, n: int, total_citations: int) -> str:
    return (
        "% Bibliography exported from NASA ADS.\n"
        "%\n"
        f"% citations_updated: {today}\n"
        "%   Generated by scripts/sync_ads.py -- do not hand-edit; re-run the\n"
        "%   script instead. The site reads the date above and labels the\n"
        "%   citation totals with it.\n"
        f"%   {n} records, {total_citations} citations at the time of writing.\n"
        f"%   Live counts: https://ui.adsabs.harvard.edu/search/q=orcid%3A{ORCID}\n"
        "\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true",
                    help="report what would change without writing files")
    args = ap.parse_args()

    token = os.environ.get("ADS_TOKEN", "").strip()
    if not token:
        print(
            "ADS_TOKEN is not set.\n"
            "  Get a free token at https://ui.adsabs.harvard.edu/user/settings/token\n"
            "  Locally:  export ADS_TOKEN=...\n"
            "  In CI:    add it as the repository secret ADS_TOKEN",
            file=sys.stderr,
        )
        return 2

    excluded = set()
    if EXCLUDE.exists():
        excluded = {
            line.split("#")[0].strip()
            for line in EXCLUDE.read_text().splitlines()
            if line.split("#")[0].strip()
        }

    try:
        records = fetch_records(token)
    except urllib.error.HTTPError as e:
        detail = e.read().decode(errors="replace")[:300]
        print(f"ADS request failed: {e.code} {e.reason}\n{detail}", file=sys.stderr)
        return 1

    print(f"  ADS returned {len(records)} records for ORCID {ORCID}")

    kept = [
        r for r in records
        if r["bibcode"] not in excluded
        and r.get("doctype", "article") in KEEP_DOCTYPES
    ]
    dropped = len(records) - len(kept)
    if dropped:
        print(f"  skipped {dropped} (excluded or non-publication doctype)")

    counts = {r["bibcode"]: int(r.get("citation_count", 0) or 0) for r in kept}
    bibcodes = [r["bibcode"] for r in kept]

    bibtex = inject_citation_counts(fetch_bibtex(bibcodes, token), counts)
    today = dt.date.today().isoformat()
    new = header(today, len(kept), sum(counts.values())) + bibtex.strip() + "\n"

    old = BIB.read_text() if BIB.exists() else ""

    def entries(text: str) -> set[str]:
        return set(re.findall(r"@[A-Za-z]+\{([^,]+),", text))

    added = entries(new) - entries(old)
    removed = entries(old) - entries(new)
    for b in sorted(added):
        print(f"  + {b}")
    for b in sorted(removed):
        print(f"  - {b}")

    # Compare ignoring the date stamp, so an unchanged bibliography is a no-op.
    strip_date = lambda t: re.sub(r"% citations_updated: \d{4}-\d{2}-\d{2}", "", t)
    if strip_date(old) == strip_date(new):
        print("  bibliography unchanged")
        return 0

    if args.dry_run:
        print("  (dry run: nothing written)")
        return 0

    BIB.write_text(new)
    print(f"  wrote {BIB}")
    return subprocess.run([sys.executable, "scripts/bib_to_data.py"], check=False).returncode


if __name__ == "__main__":
    sys.exit(main())
